server:
  port: 8080
  servlet:
    context-path: /number-verification/v2

spring:
  application:
    name: number-verification-api
  security:
    oauth2:
      resourceserver:
        jwt:
          # Telekom MACE Authorization Server configuration
          issuer-uri: http://localhost:59697/
          jwk-set-uri: http://localhost:59697/.well-known/jwks.json

jwe:
  decryption:
    # create this file before running
    # sudo mkdir -p /opt/CAMARA/resourceservers/numberverification/
    # sudo chown -R ${whoami} /opt/CAMARA/
    # sudo genrsa -out /opt/CAMARA/resourceservers/numberverification/private-key.pem
    private-key-path: ${CAMARA_NUMBERVERIFICATION_RESOURCESERVER_PRIVATE_KEY_PATH:/opt/CAMARA/resourceservers/numberverification/private-key.pem}
    key-algorithm: ${CAMARA_NUMBERVERIFICATION_RESOURCESERVER_KEY_ALGORITHM:RSA-OAEP-256}
    # Algorithm used for content encryption
    content-algorithm: ${CAMARA_NUMBERVERIFICATION_RESOURCESERVER_CONTENT_ALGORITHM:A256GCM}

logging:
  level:
    org.springframework.security: DEBUG
    com.telekom.camara: DEBUG
